select
	row_number() over () "No",
	wi."Fields"->>'System.AreaLevel2' "Team",
	wi."Fields"->>'System.IterationLevel2' "Sprint",
	wi."Fields"->>'System.Id' "ID",
	concat('https://dev.azure.com/AssetHealthInsights/Asset%20Backlogs/_workitems/edit/', wi."Fields"->>'System.Id') "US Link",
	wi."Fields"->>'System.Title' "Title",
    wi."Fields"->>'Microsoft.VSTS.Scheduling.StoryPoints' "Story Points",
    wi."Fields"->'Custom.FEby'->>'UniqueName' "FE by",
    wi."Fields"->'Custom.BEby'->>'UniqueName' "BE by",
    wi."Fields"->>'System.State' "US Status",
    wi."Fields"->>'Custom.TotalDevEffort' as "Estimated Dev Effort",
    wi."Fields"->>'Custom.TotalQCEffort' as "Estimated QC Effort",
    wi."Fields"->>'Custom.TotalBAEffort' as "Estimated BA Effort",
    wi."Fields"->>'Custom.TotalDevOpsEffort' as "Estimated DevOps Effort",
    (
        coalesce((wi."Fields"->>'Custom.TotalDevEffort')::float, 0) 
        + coalesce((wi."Fields"->>'Custom.TotalQCEffort')::float, 0) 
        + coalesce((wi."Fields"->>'Custom.TotalBAEffort')::float, 0)
        + coalesce((wi."Fields"->>'Custom.TotalDevOpsEffort')::float, 0)
    ) as "Estimated Total Effort",
    (wi."Fields"->>'Custom.DEVStartDate')::timestamp as "Actual Start Date",
    (wi."Fields"->>'Custom.USDueDate')::timestamp as "Expected UAT Date",
    (wi."Fields"->>'Custom.ActualUATDate')::timestamp as "Actual UAT Date",
    (wi."Fields"->>'Custom.ActualUATDate')::timestamp <= (wi."Fields"->>'Custom.USDueDate')::timestamp as "Delivery On Time"
from
	public."WorkItems" wi
where
	wi."Type" = 'User Story';