FROM mcr.microsoft.com/dotnet/sdk:3.1.423-bullseye-arm64v8 AS build

ENV PATH="$PATH:/root/.dotnet/tools"

RUN dotnet tool install dotnet-roundhouse -g --version 1.3.1
WORKDIR /workspace
COPY Migrations/ ./Migrations/
COPY Resources/Docker/migrate.sh ./migrate.sh
RUN chmod +x ./migrate.sh

ENTRYPOINT [ "./migrate.sh" ]