// <auto-generated />
using System;
using AdoReport.WorkerApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AdoReport.WorkerApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250306161521_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdoReport.WorkerApp.Models.WorkItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ChangedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaPath");

                    b.HasIndex("AssignedTo");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AssignedTo"), "gin");

                    b.HasIndex("ChangedDate");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("ParentId");

                    b.HasIndex("State");

                    b.HasIndex("Type");

                    b.ToTable("WorkItems", (string)null);
                });

            modelBuilder.Entity("AdoReport.WorkerApp.Models.WorkItemFieldEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FieldData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FieldData")
                        .HasDatabaseName("IX_WorkItemFields_FieldData");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FieldData"), "gin");

                    b.HasIndex("FieldName")
                        .HasDatabaseName("IX_WorkItemFields_FieldName");

                    b.HasIndex("WorkItemId", "FieldName")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkItemFields_WorkItemId_FieldName");

                    b.ToTable("WorkItemFields", (string)null);
                });

            modelBuilder.Entity("AdoReport.WorkerApp.Models.WorkItemFieldEntity", b =>
                {
                    b.HasOne("AdoReport.WorkerApp.Models.WorkItemEntity", "WorkItem")
                        .WithMany("Fields")
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("AdoReport.WorkerApp.Models.WorkItemEntity", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
